paths:
  base_output: output
  logs_dir: eval/logging/runs/v0/sbert_fix
  prompt_path: prompts/hlj_fallback_by_sbert_prompt.md
  meta_yaml: output/meta_70b.yaml
models:
  sbert: all-MiniLM-L6-v2
  folders:
  - gpt41
  - meta70b
  - opus4
  baseline: gpt41
thresholds:
  confidence: 0.75
  similarity: 0.75
  clamp_min: 0.7
  clamp_max: 0.99
semantic_eval:
  csv_out: eval/semantic_eval_results.csv
plots:
  value_col: similarity
  index_col: req_id
  columns_col: model
  title: 'Semantic Similarity: Model Diff'
  aliases:
    GPT-4.1: gpt41
    gpt-4.1: gpt41
    Meta-70B: meta70b
  plots_dir: eval/plots
eval_heatmaps:
  plots:
  - csv_path: eval/semantic_eval_results.csv
    value_col: similarity
    index_col: req_id
    columns_col: model
    out_path: output/run/v0/plots/semantic_similarity_heatmap.png
    title: Semantic Similarity Heatmap (SBERT)
field_eval:
  meta_yaml: eval/output/meta_llama70b.yaml
  out_csv: eval/metrics/field_eval.csv
  out_md: eval/metrics/field_eval.md
scripts:
- script: scripts/step_1/sbert_confidence_score.py
  args:
  - --config
  - configs/pipeline_v0.yaml
- script: scripts/step_1/semantic_eval.py
  args:
  - --config
  - configs/pipeline_v0.yaml
- script: scripts/step_1/generate_model_diff_heatmaps.py
  args:
  - --config
  - configs/pipeline_v0.yaml
- script: scripts/step_1/generate_eval_heatmaps.py
  args:
  - --config
  - configs/pipeline_v0.yaml
globals:
  current_run_id: pipeline_20250918_052614_9d2a3a
pipeline_runs:
  pipeline_20250916_064330_0854c1:
    timestamp: '2025-09-16T06:43:30.208075'
  pipeline_20250916_070015_fc3be2:
    timestamp: '2025-09-16T07:00:15.846672'
  pipeline_20250916_070438_be13ee:
    timestamp: '2025-09-16T07:04:38.746394'
  pipeline_20250916_070753_e5c378:
    timestamp: '2025-09-16T07:07:53.920012'
  pipeline_20250918_051754_310828:
    timestamp: '2025-09-18T05:17:54.735982'
  pipeline_20250918_052346_3959a4:
    timestamp: '2025-09-18T05:23:46.506383'
  pipeline_20250918_052614_9d2a3a:
    timestamp: '2025-09-18T05:26:14.520610'
